title: UNSW DataSoc
description: UNSW Data Science Society
logo: /assets/images/favicon.png
permalink: pretty
collections:
  publications:
    output: true
    permalink: /publications/:path/
  posts:
    permalink: /blog/:year/:month/:day/:title/
  team:
    sort_by: order

# Google Analytics
google_analytics: UA-187021387-1